site_name: py-script Docs
site_url: https://giraycoskun.dev
theme:
  name: material
  logo: assets/logo.ico
  favicon: assets/logo.ico
  features:
    - content.code.copy
  palette:
  # Palette toggle for light mode
    - scheme: default
      primary: lime
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: lime
      toggle:
        icon: material/brightness-4
      name: Switch to light mode

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          extra:
            show_root_heading: false
            show_source: true
            show_signature_annotations: true
            show_undoc_members: true

markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: index.md
  - getting-started.md
  - usage.md
  - Reference: reference.md